In [1]:
import pandas as pd
import numpy as np
import math
from sklearn.naive_bayes import ComplementNB,MultinomialNB
from sklearn.metrics import accuracy_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from skmultilearn.problem_transform import BinaryRelevance,ClassifierChain,LabelPowerset

In [2]:
traindf = pd.read_csv('./Data/train.csv')
traindf['abstract'] = traindf['abstract'].apply(lambda abstract: abstract.strip('[]').split(', '))
traindf['title'] = traindf['title'].apply(lambda title: title.strip('[]').split(', '))
traindf['authors'] = traindf['authors'].apply(lambda authors: authors.strip('[]').split(', '))

Combine title and abstract into a string for each article:

In [3]:
traindf['combined_text'] = (traindf.title+traindf.abstract).apply(lambda text: ' '.join(text))

Target Labels: (101 labels)

In [4]:
def targetLabels(authorData):
    labels = np.zeros((len(authorData),101))
    for i, article in enumerate(authorData):
        prolific = False
        for j, author in enumerate(article):
            author = int(author)
            if author < 100:
                prolific = True
                labels[i][author] = 1
        if not prolific:
            labels[i][100] = 1
    return labels

def createTargetColumns(traindf):
    targets = targetLabels(traindf['authors'])
    for label in range(101):
        traindf[str(label)] = [targets[article, label] for article in range(traindf.shape[0])]
    return traindf

In [5]:
trainLabels = targetLabels(traindf['authors'])

Identifying prolific articles:

In [6]:
train_prolific_ids = np.array([article_id for article_id in range(trainLabels.shape[0]) 
                               if np.sum(trainLabels[article_id][:100]) > 0])
print(train_prolific_ids)

[    0     1     3 ... 25778 25781 25788]


Identifying non-prolific articles:

In [7]:
train_nonprolific_ids = np.array([article_id for article_id in range(trainLabels.shape[0]) 
                               if np.sum(trainLabels[article_id][:100]) == 0])
print(train_nonprolific_ids)

[    2     5     6 ... 25790 25791 25792]


Create training sample with 25% non-prolific articles: (includes all prolific articles)

In [8]:
rnd = np.random.RandomState(10)

nonprolific_prop = 0.25
n_prolific = train_prolific_ids.shape[0]
n_articles = traindf.shape[0]
n_nonprolific_samples = math.floor(nonprolific_prop/(1-nonprolific_prop)*n_prolific)

train_nonprolific_sample_ids = rnd.choice(train_nonprolific_ids, size = n_nonprolific_samples, replace = False)

print(train_nonprolific_sample_ids)

[17578 16901   215 ... 23474  7669 17056]


In [9]:
training_sample_ids = np.concatenate((train_prolific_ids, train_nonprolific_sample_ids), axis=0)

training_sample = traindf.iloc[training_sample_ids]

Sample labels:

In [10]:
sampleLabels = targetLabels(training_sample['authors'])

Split data into train and test sets:

In [11]:
trainData, testData, labelsTrain, labelsTest = train_test_split(training_sample, sampleLabels, 
                                                                        test_size=0.25, random_state=42)

Extracting coauthor and venue features:

In [12]:
def coauthorsFeatures(authorData):
    coauthors = np.zeros((len(authorData), 21246),dtype=np.int8)
    for i, article in enumerate(authorData):
        for j, author in enumerate(article):
            try:
                author = int(author)
                if author > 99:
                    coauthors[i][author] = 1
            except:
                pass
    return coauthors

def venueFeatures(venueData):
    venues = np.zeros((len(venueData), 465), dtype=np.int8)
    for i, venue in enumerate(venueData):
        if not np.isnan(venue):
            venues[i][int(venue)] = 1
    return venues

In [13]:
trainCoauthors = coauthorsFeatures(trainData['authors'])
trainVenues = venueFeatures(trainData['venue'])

testCoauthors = coauthorsFeatures(testData['authors'])
testVenues = venueFeatures(testData['venue'])

Implementing Tf-Idf and obtaining features for text in trainData articles:

In [14]:
tfidf = TfidfVectorizer()
trainTextfeatures = tfidf.fit_transform(trainData['combined_text']).toarray()

testTextfeatures = tfidf.transform(testData['combined_text']).toarray()

Concatenate features:

In [15]:
trainFeatures = np.concatenate((trainCoauthors, trainVenues, trainTextfeatures), axis=1)

testFeatures = np.concatenate((testCoauthors, testVenues, testTextfeatures), axis=1)

## Binary Relevance with Multinomial NB:

In [16]:
model = BinaryRelevance(MultinomialNB())
model.fit(trainFeatures,labelsTrain)
test_preds = model.predict(testFeatures)
acc = accuracy_score(labelsTest, test_preds)
f1 = f1_score(labelsTest, test_preds, average="samples")
result = {"accuracy:": acc, "f1_score": f1}
print(result)

{'accuracy:': 0.04221954161640531, 'f1_score': 0.04267877327232002}


## Binary Relevance with Complement NB:

In [17]:
model = BinaryRelevance(ComplementNB())
model.fit(trainFeatures,labelsTrain)
test_preds = model.predict(testFeatures)
acc = accuracy_score(labelsTest, test_preds)
f1 = f1_score(labelsTest, test_preds, average="samples")
result = {"accuracy:": acc, "f1_score": f1}
print(result)

{'accuracy:': 0.07076799356654603, 'f1_score': 0.07212695486669587}


## Classifier Chain with Multinomial NB:

In [18]:
model = ClassifierChain(MultinomialNB())
model.fit(trainFeatures,labelsTrain)
test_preds = model.predict(testFeatures)
acc = accuracy_score(labelsTest, test_preds)
f1 = f1_score(labelsTest, test_preds, average="samples")
result = {"accuracy:": acc, "f1_score": f1}
print(result)

{'accuracy:': 0.0607157217531162, 'f1_score': 0.06129205200375285}


## Classifier Chain with Complement NB:

In [19]:
model = ClassifierChain(ComplementNB())
model.fit(trainFeatures,labelsTrain)
test_preds = model.predict(testFeatures)
acc = accuracy_score(labelsTest, test_preds)
f1 = f1_score(labelsTest, test_preds, average="samples")
result = {"accuracy:": acc, "f1_score": f1}
print(result)

{'accuracy:': 0.11137917169280258, 'f1_score': 0.11318126987608292}


## Label Powerset with Multinomial NB:

In [20]:
model = LabelPowerset(MultinomialNB())
model.fit(trainFeatures,labelsTrain)
test_preds = model.predict(testFeatures)
acc = accuracy_score(labelsTest, test_preds)
f1 = f1_score(labelsTest, test_preds, average="samples")
result = {"accuracy:": acc, "f1_score": f1}
print(result)

{'accuracy:': 0.24567752312022517, 'f1_score': 0.24567752312022517}


## Label Powerset with Complement NB:

In [21]:
model = LabelPowerset(ComplementNB())
model.fit(trainFeatures,labelsTrain)
test_preds = model.predict(testFeatures)
acc = accuracy_score(labelsTest, test_preds)
f1 = f1_score(labelsTest, test_preds, average="samples")
result = {"accuracy:": acc, "f1_score": f1}
print(result)

{'accuracy:': 0.6328910333735425, 'f1_score': 0.6806479407203171}


## Predict test set using Label Powerset with Complement NB:

### Model using full training data sample

Features and Tf-Idf for training sample: (Sample labels were calculated earlier: 'sampleLabels')

In [22]:
tfidf = TfidfVectorizer()
sampleTextfeatures = tfidf.fit_transform(training_sample['combined_text']).toarray()

sampleCoauthors = coauthorsFeatures(training_sample['authors'])
sampleVenues = venueFeatures(training_sample['venue'])

sampleFeatures = np.concatenate((sampleCoauthors, sampleVenues, sampleTextfeatures), axis=1)

Fitting model:

In [23]:
fullmodel = LabelPowerset(ComplementNB())
fullmodel.fit(sampleFeatures,sampleLabels)

LabelPowerset(classifier=ComplementNB(), require_dense=[True, True])

Training metrics:

In [24]:
fullmodel_predictions = fullmodel.predict(sampleFeatures)
acc = accuracy_score(sampleLabels, fullmodel_predictions)
f1 = f1_score(sampleLabels, fullmodel_predictions, average="samples")
result = {"accuracy:": acc, "f1_score": f1}
print(result)

{'accuracy:': 0.8523024331389504, 'f1_score': 0.8802232053086668}


Test Data:

In [25]:
testdf = pd.read_csv('./Data/test.csv')
testdf['abstract'] = testdf['abstract'].apply(lambda abstract: abstract.strip('[]').split(', '))
testdf['title'] = testdf['title'].apply(lambda title: title.strip('[]').split(', '))
testdf['coauthors'] = testdf['coauthors'].apply(lambda authors: authors.strip('[]').split(', '))

testdf['combined_text'] = (testdf.title+testdf.abstract).apply(lambda text: ' '.join(text))

Test Features:

In [26]:
testTextfeatures = tfidf.transform(testdf['combined_text']).toarray()

testCoauthors = coauthorsFeatures(testdf['coauthors'])
testVenues = venueFeatures(testdf['venue'])

testFeatures = np.concatenate((testCoauthors, testVenues, testTextfeatures), axis=1)

## Test predictions:

In [27]:
test_predictions = fullmodel.predict(testFeatures)

Create submission:

In [28]:
def createSubmission(predictions, testdf, filename):
    predDf = pd.DataFrame(data={'Id': [i for i in testdf['identifier']], 'Predict': [None for _ in range(testdf.shape[0])]})
    for i in range(testdf.shape[0]):
        if predictions[i,100] == 1:
            predDf['Predict'][i] = '-1'
            continue
        pred_str = ''
        for j in range(100):
            if predictions[i,j] == 1:
                pred_str = ' '.join((pred_str, str(j))).strip()
        if len(pred_str) == 0:
            pred_str = '-1'
        predDf['Predict'][i] = pred_str
    predDf.to_csv(filename, sep=',', index=False)
    print(f'Saved predictions to {filename}')
    return predDf                

In [29]:
createSubmission(test_predictions, testdf, 'LabelPowerset_ComplementNB_25percentSample_preds_1.2.csv')

<ipython-input-28-da4abb66af2d>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predDf['Predict'][i] = pred_str
<ipython-input-28-da4abb66af2d>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predDf['Predict'][i] = '-1'


Saved predictions to LabelPowerset_ComplementNB_25percentSample_preds_1.2.csv


Id Predict
0      0      92
1      1      -1
2      2      31
3      3      23
4      4      32
..   ...     ...
795  795      54
796  796      97
797  797      13
798  798      71
799  799      43

[800 rows x 2 columns]